title: My Blog
description: Contains my experiences in the world of computer science and some other stuff too ;).

url: http://uditgulati.github.com/blog
baseurl: "/blog"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: uditgulati
   facebook: udit.gulati.790
   email: uditgulati0@gmail.com

google_analytics: "UA-58263416-1"
